# Generated by Django 5.0.4 on 2024-05-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone_no', models.IntegerField()),
                ('vehicle_reg_no', models.CharField(max_length=10)),
                ('login_time', models.DateTimeField(verbose_name='last seen')),
            ],
        ),
    ]
